name: meetox
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  cached_network_image: ^3.2.3
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  file_picker: ^5.3.3
  fl_query: ^1.0.0-alpha.3
  fl_query_hooks: ^1.0.0-alpha.3
  flutter:
    sdk: flutter
  flutter_appauth: ^6.0.1
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.18.6
  flutter_map_tile_caching: ^9.0.0-dev.3
  flutter_remix: ^0.0.3
  flutter_screenutil: ^5.9.0-beta
  get: ^5.0.0-release-candidate-4
  get_storage: ^2.1.1
  loading_animation_widget: ^1.2.0+4
  smooth_page_indicator: ^1.1.0
  supabase_flutter: ^1.10.9
  flutter_svg: ^2.0.7
  image_picker: ^1.0.1
  timeago: ^3.5.0
  timeago_flutter: ^3.5.0


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/brand/
    - assets/avatars/
    - assets/circle_avatars/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf