name: meetox
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  cached_network_image: ^3.2.3
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  custom_navigation_bar: ^0.8.2
  date_format: ^2.0.7
  ficonsax: ^0.0.3
  file_picker: ^5.3.3
  fl_query: ^1.0.0-alpha.3
  fl_query_hooks: ^1.0.0-alpha.3
  fl_query_connectivity_plus_adapter: ^0.1.0-alpha.2
  flutter:
    sdk: flutter
  flutter_appauth: ^6.0.1
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.18.6
  flutter_map: ^4.0.0
  flutter_map_tile_caching: ^8.0.0
  flutter_remix: ^0.0.3
  flutter_screenutil: ^5.9.0-beta
  flutter_zoom_drawer: ^3.1.1
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get: ^5.0.0-release-candidate-4
  get_storage: ^2.1.1
  http: ^0.13.5
  infinite_scroll_pagination: ^4.0.0-dev.1
  flutter_keyboard_visibility: ^5.4.1
  latlong2: ^0.8.1
  loading_animation_widget: ^1.2.0+4
  lottie: ^2.5.0
  permission_handler: ^10.4.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  supabase_flutter: ^1.10.9
  flutter_svg: ^2.0.7
  image_picker: ^1.0.1
  timeago: ^3.5.0
  timeago_flutter: ^3.5.0
  path_provider: ^2.0.15
  url_launcher: ^6.1.12
  flutter_map_marker_cluster:
    git:
      url: https://github.com/nploi/flutter_map_marker_cluster
      ref: upgrade_flutter_map_v4




dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/brand/
    - assets/avatars/
    - assets/circle_avatars/
    - assets/images/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf